DROP TABLE IF EXISTS book;

CREATE TABLE book(
   book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   book_name varchar(50)not null,
   book_author varchar(50)not null,
   book_year int CHECK(book_year>1700),
   person_id integer REFERENCES person(person_id)ON DELETE SET NULL
);
SELECT * FROM person;
INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone','Michael Murkok',1988,1);
INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('The Endless Book','Bastian Baltazar',1999,2);
INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Summer in heliconia','Bryan Oldiss',1956,3);
INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone1','Michael Murkokf',1975,4);
INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone2','Michael Murkok6',1944,3);
INSERT INTO book(book_name,book_author,book_year,person_id)VALUES('Elrik from Melnibone3','Michael Murkok4',1992,1);
SELECT * FROM book;