DROP TABLE IF EXISTS person;
CREATE TABLE person(
    person_id int GENERATED BY DEFAULT AS IDENTITY,
	name varchar(30)not null,
	age integer check(age>0),
	email varchar(30) not null UNIQUE,
	PRIMARY KEY(person_id)
);
INSERT INTO person(name,age,email) VALUES('Timur',19,'tirukilum09@gmail.com');
INSERT INTO person(name,age,email) VALUES('Jumbluqing',18,'sepherhervar@gmail.com');
INSERT INTO person(name,age,email) VALUES('Qollungirqi',27,'chansanuka@gmail.com');
--INSERT INTO person(name,age,email) VALUES('Arridjakren',-1,'chansanukali@gmail.com');


SELECT * FROM person;
--SELECT * FROM person_person_id_seq;


DROP SEQUENCE first_sequence;
CREATE SEQUENCE first_sequence;
SELECT nextval('first_sequence');